# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: tuyen-tit
# google_analytics: dbyll
title: dev nông

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: hi, Bro! Hôm nay thế nào?

description: Simple developer (nông dân, công nông)
author:
  name: Nông
  email: tuyennt.cv@gmail.com
  github: minimal-dev
  # twitter: dbtek
  # pinterest: asd123
  # linkedin: asd123
  bio: Simple developer
  email_md5: 02d58eaa30573919879f7134196c48ac

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
